force-app/main/default/objects/Opportunity_Qualification__c/Opportunity_Qualification__c.object-meta.xml
<CustomObject>
    <label>Opportunity Qualification</label>
    <nameField>
        <displayFormat>Q-{00}</displayFormat>
        <label>Opportunity Qualification  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Qualifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_Qualification_Ques__c/Opportunity_Qualification_Ques__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Opportunity Qualification</label>
</CustomObject>

force-app/main/default/objects/Opportunity_Win_Plan_templates__c/Opportunity_Win_Plan_templates__c.object-meta.xml
<CustomObject>
    <label>Opportunity Win Plan templates</label>
    <nameField>
        <displayFormat>OPW-{0000}</displayFormat>
        <label>Opportunity Win Plan templates Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Win Plan templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_Win_Plan_templates__c/fields/Customer_Reason_for_Taking_Action__c.field-meta.xml
<CustomField>
    <fullName>Customer_Reason_for_Taking_Action__c</fullName>
    <label>Customer Reason for Taking Action</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity_Win_Plan_templates__c/fields/Date_1__c.field-meta.xml
<CustomField>
    <fullName>Date_1__c</fullName>
    <label>Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity_Win_Plan_templates__c/fields/Evidence_1__c.field-meta.xml
<CustomField>
    <fullName>Evidence_1__c</fullName>
    <label>Evidence</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity_Win_Plan_templates__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity Win Plan templates</relationshipLabel>
    <relationshipName>Opportunity_Win_Plan_templates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity_Win_Plan_templates__c/fields/Opportunity_Qualification__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Qualification__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity Qualification</label>
    <referenceTo>Opportunity_Qualification__c</referenceTo>
    <relationshipLabel>Opportunity Win Plan templates</relationshipLabel>
    <relationshipName>Opportunity_Win_Plan_templates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity_Win_Plan_templates__c/fields/Overview_of_the_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Overview_of_the_Opportunity__c</fullName>
    <label>Overview of the Opportunity</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/OptyWinExtension.cls
public with sharing class OptyWinExtension {
  
  public List<Opportunity_Win_Plan_templates__c> oppWin {get;set;}
  public Opportunity oppty{get;set;}
  public string customer {get;set;}
  public string opptyPOC {get;set;}
  public List<Opportunity_Qualification_Ques__c> Ques {get;set;}
  public List<Opportunity_Qualification__c> oQObj {get;set;} 
  public List<questionWrapper> questionList {get; set;}
  public id opptyId;
  
  public class questionWrapper{
  	public string question {get;set;}
  	public date dates {get;set;}
  	public string evidence {get;set;}
  	public string questionId;
  	/*public questionWrapper(string q,Date d,string e){
  		question=q;
  		dates=d;
  		evidence=e;
  	}*/
  }
  
  public OptyWinExtension(ApexPages.StandardController stdCtrl)
   {
    //stdCtrl.addFields(new List<String>{'Account.name,owner.name'});
    //oppty=(Opportunity) stdCtrl.getRecord();
    opptyId=ApexPages.currentPage().getParameters().get('id');
    oppty=[Select id,owner.name,Account.name,Overview_of_the_Opportunity__c,Customer_Reason_for_Taking_Action__c 
    																							from Opportunity 
    																							where id=:opptyId];
    customer=oppty.Account.name;
    opptyPOC=oppty.owner.name;
    /*oppWin=new List<Opportunity_Win_Plan_templates__c>([Select id,Opportunity_Qualification__r.Question__c,Date_1__c,Evidence_1__c
    											from Opportunity_Win_Plan_templates__c
    											Where Opportunity__c=:opptyId order By Opportunity_Qualification__r.Question__c ASC]);*/
    /*Map<String,Opportunity_Qualification_Ques__c> allQues = Opportunity_Qualification_Ques__c.getAll();
    Ques = allQues.values();
    Ques.sort();
    for(Opportunity_Qualification_Ques__c q :Ques){
    	system.debug('#####Questions '+q.Question__c);
    	tr = new questionWrapper();
        tr.question = q.Question__c;
        RowList.add(tr);
        RowList.add(new questionWrapper('sambit'));
        }*/
    questionList= new List<questionWrapper>();
    questionWrapper qW;    
    for(Opportunity_Qualification__c oQ:[Select id,Question__c from Opportunity_Qualification__c order by Name]){
    	qW=new questionWrapper();
    	qW.question=oQ.Question__c;
    	//qW.dates='';
    	qW.evidence='';
    	qW.questionId=oQ.id;
    	questionList.add(qW);
    }
   }
   
  public pagereference SaveOptyWin(){
  	 		
   	List<Opportunity_Win_Plan_templates__c> toUpsertList=new List<Opportunity_Win_Plan_templates__c>();
   	
   	for(questionWrapper oW:questionList){
   		toUpsertList.add(new Opportunity_Win_Plan_templates__c(Opportunity__c=opptyId,Opportunity_Qualification__c=oW.questionId,Date_1__c=oW.dates,Evidence_1__c=oW.evidence));
   	}
   	
   	upsert toUpsertList;  
   	return (new pagereference('/'+opptyId));		
   	
   }
   

}