force-app/main/default/objects/Login__c/Login__c.object-meta.xml
<CustomObject>
    <label>Login</label>
    <nameField>
        <displayFormat>LOGIN_{0}</displayFormat>
        <label>Login Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logins</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Login__c/fields/Employee_ID__c.field-meta.xml
<CustomField>
    <fullName>Employee_ID__c</fullName>
    <label>Employee ID</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/login.cls
public with sharing class login{

String username;
String password;

public String getusername() {return username;}
public void setusername(String un){this.username=un;}
public String getpassword() {return password;}
public void setpassword(String pw){this.password=pw;}



public PageReference Login12()
{
    List<login__c> a = [select id from login__c where   Employee_ID__c =:username and Password__c=:password];
    system.debug('user::::::::::::::::::::::::::::::::::::::::::::::::'+a);
    if(a.size()==0)
    {
    ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,'Invalid UserName or Password'));
    return null;
    }
    else
    {
        system.debug('username:::::::::::::::::::::::::::::::::::::::::::::::::::::::::'+username);
        PageReference p= new PageReference('https://ap1.salesforce.com/setup/ui/recordtypeselect.jsp?ent=Contact&retURL=%2F003%2Fo&save_new_url=%2F003%2Fe%3FretURL%3D%252F003%252Fo');
        system.debug('password::::::::::::::::::::::::::::::::::::::::::::::::'+password);
        p.setRedirect(true);
       return p;
    }

}

}